# Generated by Django 4.2.5 on 2023-10-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_courses1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(),
        ),
    ]
